security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Rendonan\MiniBundle\Entity\Account: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: RendonanMiniBundle:Account, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: rendonan_mini_login
                check_path: rendonan_mini_login_check

    access_control:
        - { path: ^/login,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/checklogin,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }