rendonan_mini_homepage:
    path:     /main
    defaults: { _controller: RendonanMiniBundle:Main:index }

rendonan_mini_game:
    path:     /game
    defaults: { _controller: RendonanMiniBundle:Game:index }

rendonan_mini_gameload:
    pattern:  /gameload
    defaults: { _controller: RendonanMiniBundle:Game:loaddata }

rendonan_mini_gamesave:
    pattern:  /gamesave
    defaults: { _controller: RendonanMiniBundle:Game:savedata }

rendonan_mini_scores:
    path:     /highscore
    defaults: { _controller: RendonanMiniBundle:Highscore:index }

rendonan_mini_scoresave:
    path:     /scoresave
    defaults: { _controller: RendonanMiniBundle:Highscore:scoresave }

rendonan_mini_registration:
    path:     /register
    defaults: { _controller: RendonanMiniBundle:Register:index }

rendonan_mini_thankyou:
    path:     /thankyou
    defaults: { _controller: RendonanMiniBundle:Register:thankyou }

rendonan_mini_login:
    path:     /login
    defaults: { _controller: RendonanMiniBundle:Register:login }

rendonan_mini_logout:
    pattern:  /logout
    defaults: { _controller: RendonanMiniBundle:Register:logout }

rendonan_mini_404:
    path:     /{url}
    defaults: { _controller: RendonanMiniBundle:PageNotFound:index }
    requirements:
        url:  .*$